version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
