version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: docker-service/backend/Dockerfile
    restart: unless-stopped
  proxy:
    build:
      context: .
      dockerfile: docker-service/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
